### ISSUE TITLE
not working when FacJam.py file run

### ISSUE THREAD

**Issue by Ritz5940** [ctralie/FaceJam#2]
$ python FaceJam.py --songfilename "02 - Nashe Si Chadh Gayi (320 Kbps) - DownloadMing.SE.wav" --imgfilename "scan0316.jpg" --videoname "myvideo.avi"
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-3:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-4:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-6:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-8:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-7:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-5:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-9:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-10:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-11:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-12:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-14:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-13:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-15:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>
Process SpawnPoolWorker-16:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Python35\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'makeWarpsBatch' on <module '__mp_main__' from 'C:\\Users\\hp\\FaceJam\\FaceJam.py'>

**Comment by ctralie** [comment]
Hello!  Thank you for your interest in this!  Unfortunately, I'm not going
to have time to fix this for a little while...the semester is starting in
two weeks with remote classes.  But I will get to this as soon as I can
